language:
  - python
  
python:
  - "2.7"
  
env:
  - secure: "qPP4XRrdoPtpwpG4PwxptbB/DqYcvdFUFm5nxbBCnjENPk4+yz3bZst+ytlcr1J/Fi4EoYYmL1t+UW+hu5jZ4twiHOstjB6qlLEuQyXy/Poq8EX9isukxUYZGhl5ZtvbGrPIVvHvG2iNIoP6S+8rv3H81/hWRVRB3mO0QW6OBpk="
  - secure: "GPJ0w3Awc5rgjTSYzNaDycMdiZ6wAOslXcjkaGMCS9ZMlv5vExzDT/aLVd7ouj7e+ajR7vy26J2sRCnUGcHibzx36DNHS++qzwYmuev6va1y/+JXjasBqgc51k8GaVjeRyXPnbU2ZlGqkcoKAIhuHHSoe3G6SUhFKZhJH8XaAFQ="
install:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.14.zip
  - unzip -q google_appengine_1.9.14.zip
  - pip install webtest
  
after_success:
  - ./google_appengine/appcfg.py --oauth2_access_token=$ACCESS_TOKEN -A dascastsgaeone update .
  
script:
  - python test.py